const config = {
    darkMode: ["class"],
    content: [
        "./src/pages/**/*.{js,jsx,mdx}",
        "./src/components/**/*.{js,jsx,mdx}",
        "./src/app/**/*.{js,jsx,mdx}",
    ],
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                msu: {
                    blue: "var(--msu-blue)",
                    gold: "var(--msu-gold)",
                    lite: "var(--msu-lite)",
                    warm: "var(--msu-warm)",
                },
                neutral: {
                    white: "var(--neutral-white, #ffffff)",
                    50: "var(--neutral-50, #f8f8f7)",
                    100: "var(--neutral-100, #eeede9)",
                    200: "var(--neutral-200, #dedcd6)",
                    400: "var(--neutral-400, #a09d95)",
                    500: "var(--neutral-500, #73706a)",
                    700: "var(--neutral-700, #3d3b37)",
                    900: "var(--neutral-900, #1a1917)",
                },
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                    50: '#f0f5fa',
                    100: '#d6e4f0',
                    200: '#a8c5de',
                    300: '#6a9bc4',
                    400: '#3d74a6',
                    500: '#1a4f7f',
                    600: '#003a66',
                    700: '#002d52',
                    800: '#002144',
                    900: '#001836',
                },
                success: {
                    light: '#10B981',
                    dark: '#34D399',
                    bg: '#ECFDF5',
                    bgDark: '#064E3B',
                },
                warning: {
                    light: '#F59E0B',
                    dark: '#FBBF24',
                    bg: '#FFFBEB',
                    bgDark: '#78350F',
                },
                error: {
                    light: '#EF4444',
                    dark: '#F87171',
                    bg: '#FEF2F2',
                    bgDark: '#7F1D1D',
                },
                info: {
                    light: '#3B82F6',
                    dark: '#60A5FA',
                    bg: '#EFF6FF',
                    bgDark: '#1E3A8A',
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                calendar: {
                    personal: '#6B7280',
                    campus: '#F59E0B',
                    officeHours: '#10B981',
                    deadline: '#EF4444',
                    teaching: '#2563EB',
                    meeting: '#3B82F6',
                    event: '#F59E0B',
                },
                status: {
                    online: '#22C55E',
                    away: '#FBBF24',
                    busy: '#EF4444',
                    offline: '#6B7280',
                },
            },
            fontFamily: {
                display: ['var(--font-display)'],
                body: ['var(--font-body)'],
                mono: ['var(--font-mono)'],
            },
            fontSize: {
                'display-xl': ['3.5rem', { lineHeight: '1.08', fontWeight: '700' }],
                'display-lg': ['2.5rem', { lineHeight: '1.1', fontWeight: '700' }],
                'display-md': ['2rem', { lineHeight: '1.15', fontWeight: '700' }],
                'heading-lg': ['1.5rem', { lineHeight: '1.25', fontWeight: '600' }],
                'heading-md': ['1.25rem', { lineHeight: '1.3', fontWeight: '600' }],
                'heading-sm': ['1.125rem', { lineHeight: '1.35', fontWeight: '600' }],
                'body-lg': ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
                'body-md': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
                'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
                'caption': ['0.75rem', { lineHeight: '1.4', fontWeight: '500' }],
            },
            spacing: {
                '4.5': '1.125rem',
                '13': '3.25rem',
                '15': '3.75rem',
                '18': '4.5rem',
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            boxShadow: {
                'sm': 'var(--shadow-sm)',
                'md': 'var(--shadow-md)',
                'lg': 'var(--shadow-lg)',
                'surface': 'var(--shadow-sm)',
                'surface-lg': 'var(--shadow-md)',
                'accent': 'var(--shadow-md)',
                'accent-lg': 'var(--shadow-lg)',
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
                'fade-in': 'fadeIn 0.3s ease-out',
                'slide-up': 'slideUp 0.3s ease-out',
                'slide-down': 'slideDown 0.3s ease-out',
                'scale-in': 'scaleIn 0.2s ease-out',
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideUp: {
                    '0%': { opacity: '0', transform: 'translateY(8px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                slideDown: {
                    '0%': { opacity: '0', transform: 'translateY(-8px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                scaleIn: {
                    '0%': { opacity: '0', transform: 'scale(0.97)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
module.exports = config;
